### ISSUE TITLE
[QA] Add missing Unit Tests on PragmaticRawValueValidator

### ISSUE THREAD

**Issue by gmorel** [imediafrance/ammit#40]
#### Pain Point

We have only 1 method Unit Tested on `Imedia\Ammit\UI\Resolver\Validator\PragmaticRawValueValidator`

#### TODO

In `tests/units/UI/Resolver/Validator/PragmaticRawValueValidator.php `
- [ ] Unit Test `mustBeUuid()`
  - `test_it_gets_value_even_if_uuid_invalid`
  - `test_it_gets_value_even_if_uuid_valid`
- [ ] Unit Test `mustHaveLengthBetween()`
  - `test_it_gets_value_even_if_length_invalid`
  - `test_it_gets_value_even_if_length_valid`
- [ ] Unit Test `mustBeEmailAddress()`
  - `test_it_gets_value_even_if_email_invalid`
  - `test_it_gets_value_even_if_email_valid`
- [ ] Rename `test_it_gets_value_even_if_string_empty_detected` 
  - into `test_it_gets_value_even_if_string_empty_invalid`
- [ ] Rename `test_it_gets_value_even_if_valid`
  - into `test_it_gets_value_even_if_string_empty_valid`

Atoum Doc:
http://atoum.org/

Unit test can be run via:
> docker/bin/php bin/atoum tests/units/UI/Resolver/Validator/PragmaticRawValueValidator.php
