### ISSUE TITLE
[Feature] Manage request header

### ISSUE THREAD

**Issue by gmorel** [imediafrance/ammit#55]
#### Pain Point

We ar eable to deal with
- Raw
- GET
- POST

We should be able to map and validate header too.

#### TODO

 - [ ] Implement `Request/PureHeaderValueValidator`
   - `mustBeString`
 - [ ] Implement `Request/PragmaticHeaderValueValidator`
   - `mustBeUuid`
- [ ] Manage Header in `AbstractPureCommandResolver`
  - [ ] Extract `attribute` + `query` into a **PureRequestValidator** in order to ease further enhancement
    - Try to avoid train wreck
    - $this->requestValidator->queryStringValueValidator->mustBeString
- [ ] Manage Header in `AbstractPragmaticCommandResolver`
  - [ ] Extract `attribute` + `query` into a **PragmaticRequestValidator** in order to ease further enhancement
    - Try to avoid train wreck
    - $this->requestValidator->queryStringValueValidator->mustBeUuid
